In [1]:
#Importing Dependencies 
import pandas as pd
import numpy as np

In [2]:
#Reading dataset 1 - FAO
csv_file = "../FAO.csv"
fao_data_df = pd.read_csv(csv_file,encoding='latin1')

In [3]:
#Insert an id column and rename column 'Item' to 'FAO_Category' for later merge
fao_data_df.insert(0, 'ID', range(0, 0 + len(fao_data_df)))
fao_data_df = fao_data_df.rename(columns={'Item':'FAO_Category'})
fao_data_df.head()

,ID,Area Abbreviation,Area Code,Area,Item Code,FAO_Category,Element Code,Element,Unit,latitude,...,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013
0,0,AFG,2,Afghanistan,2511,Wheat and products,5142,Food,1000 tonnes,33.94,...,3249.0,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895
1,1,AFG,2,Afghanistan,2805,Rice (Milled Equivalent),5142,Food,1000 tonnes,33.94,...,419.0,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422
2,2,AFG,2,Afghanistan,2513,Barley and products,5521,Feed,1000 tonnes,33.94,...,58.0,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360
3,3,AFG,2,Afghanistan,2513,Barley and products,5142,Food,1000 tonnes,33.94,...,185.0,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89
4,4,AFG,2,Afghanistan,2514,Maize and products,5521,Feed,1000 tonnes,33.94,...,120.0,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200

In [4]:
#Creating unique list of categories to normalize
FAO_ctgry_df = pd.DataFrame({'FAO_Category': list(set(fao_data_df['FAO_Category']))})
FAO_ctgry_df.to_csv('FAO_ctgry_df.csv')
FAO_ctgry_df.head()

       FAO_Category
0     Demersal Fish
1      Palm kernels
2     Groundnut Oil
3            Offals
4  Rye and products

In [5]:
#read category datagrame with new column set index to normalized category
csv_file = "FAO_norm_ctgry_df.csv"
FAO_nrm_ctgry_df = pd.read_csv(csv_file)
del FAO_nrm_ctgry_df['Unnamed: 0']
del FAO_nrm_ctgry_df['Unnamed: 3']
del FAO_nrm_ctgry_df['Unnamed: 4']
#FAO_nrm_ctgry_df = FAO_nrm_ctgry_df.rename(columns={'Unnamed: 2': 'normalized_category'})
#FAO_nrm_ctgry_df = FAO_nrm_ctgry_df.set_index('normalized_category')
#list(FAO_nrm_ctgry_df.columns.values)
FAO_nrm_ctgry_df.head()

            FAO_Category Normalized_Category
0             Sugar beet           Vegetable
1  Tomatoes and products           Vegetable
2          Starchy Roots           Vegetable
3         Palmkernel Oil                 Oil
4             Vegetables           Vegetable

In [6]:
# merge to add normalized category to FAO
fao_norm_df = pd.merge(fao_data_df, FAO_nrm_ctgry_df, on='FAO_Category', how='left')
del fao_norm_df['ID']
del fao_norm_df['Area Code']
del fao_norm_df['Element Code']
del fao_norm_df['latitude']
del fao_norm_df['longitude']
del fao_norm_df['Item Code']
fao_norm_df

,Area Abbreviation,Area,FAO_Category,Element,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,...,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Normalized_Category
0,AFG,Afghanistan,Wheat and products,Food,1000 tonnes,1928.0,1904.0,1666.0,1950.0,2001.0,...,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,Grain
1,AFG,Afghanistan,Rice (Milled Equivalent),Food,1000 tonnes,183.0,183.0,182.0,220.0,220.0,...,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,Grain
2,AFG,Afghanistan,Barley and products,Feed,1000 tonnes,76.0,76.0,76.0,76.0,76.0,...,236.0,262.0,263.0,230.0,379.0,315.0,203.0,367,360,Grain
3,AFG,Afghanistan,Barley and products,Food,1000 tonnes,237.0,237.0,237.0,238.0,238.0,...,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,Grain
4,AFG,Afghanistan,Maize and products,Feed,1000 tonnes,210.0,210.0,214.0,216.0,216.0,...,208.0,233.0,249.0,247.0,195.0,178.0,191.0,200,200,Grain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21472,ZWE,Zimbabwe,Milk - Excluding Butter,Food,1000 tonnes,230.0,232.0,234.0,238.0,234.0,...,357.0,359.0,356.0,341.0,385.0,418.0,457.0,426,451,Dairy
21473,ZWE,Zimbabwe,"Fish, Seafood",Feed,1000 tonnes,27.0,25.0,27.0,23.0,27.0,...,4.0,9.0,6.0,9.0,5.0,15.0,15.0,15,15,Seafood
21474,ZWE,Zimbabwe,"Fish, Seafood",Food,1000 tonnes,6.0,6.0,6.0,8.0,9.0,...,14.0,17.0,14.0,15.0,18.0,29.0,40.0,40,40,Seafood
21475,ZWE,Zimbabwe,"Aquatic Products, Other",Food,1000 tonnes,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,Seafood
21476,ZWE,Zimbabwe,Miscellaneous,Food,1000 tonnes,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,Other

In [10]:
#Filtereing dataset to food (as it also contains feed data)
fao_norm_df = fao_norm_df.loc[fao_norm_df['Element'] == 'Food']
fao_norm_df

,Area Abbreviation,Area,FAO_Category,Element,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,...,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Normalized_Category
0,AFG,Afghanistan,Wheat and products,Food,1000 tonnes,1928.0,1904.0,1666.0,1950.0,2001.0,...,3486.0,3704.0,4164.0,4252.0,4538.0,4605.0,4711.0,4810,4895,Grain
1,AFG,Afghanistan,Rice (Milled Equivalent),Food,1000 tonnes,183.0,183.0,182.0,220.0,220.0,...,445.0,546.0,455.0,490.0,415.0,442.0,476.0,425,422,Grain
3,AFG,Afghanistan,Barley and products,Food,1000 tonnes,237.0,237.0,237.0,238.0,238.0,...,43.0,44.0,48.0,62.0,55.0,60.0,72.0,78,89,Grain
5,AFG,Afghanistan,Maize and products,Food,1000 tonnes,403.0,403.0,410.0,415.0,415.0,...,67.0,82.0,67.0,69.0,71.0,82.0,73.0,77,76,Grain
6,AFG,Afghanistan,Millet and products,Food,1000 tonnes,17.0,18.0,19.0,20.0,21.0,...,21.0,11.0,19.0,21.0,18.0,14.0,14.0,14,12,Grain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21470,ZWE,Zimbabwe,Eggs,Food,1000 tonnes,6.0,6.0,6.0,6.0,6.0,...,18.0,18.0,21.0,22.0,27.0,27.0,24.0,24,25,Dairy
21472,ZWE,Zimbabwe,Milk - Excluding Butter,Food,1000 tonnes,230.0,232.0,234.0,238.0,234.0,...,357.0,359.0,356.0,341.0,385.0,418.0,457.0,426,451,Dairy
21474,ZWE,Zimbabwe,"Fish, Seafood",Food,1000 tonnes,6.0,6.0,6.0,8.0,9.0,...,14.0,17.0,14.0,15.0,18.0,29.0,40.0,40,40,Seafood
21475,ZWE,Zimbabwe,"Aquatic Products, Other",Food,1000 tonnes,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,Seafood
21476,ZWE,Zimbabwe,Miscellaneous,Food,1000 tonnes,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,Other

In [18]:
#Reading open foods csv- Dataset2 (required converting tsv to csv)
dfs = pd.read_csv('../Resources/foodfact.tsv', sep='\t', chunksize=50)
for df in dfs:
    df.to_csv('foodfact.csv', sep=',', mode='a')
openfood_df = pd.read_csv("en.openfoodfacts.org.products.csv")

In [21]:
#Listing all column names in csv
list(openfood_df.columns.values)

['Unnamed: 0',
 'code',
 'url',
 'creator',
 'created_t',
 'created_datetime',
 'last_modified_t',
 'last_modified_datetime',
 'product_name',
 'generic_name',
 'quantity',
 'packaging',
 'packaging_tags',
 'brands',
 'brands_tags',
 'categories',
 'categories_tags',
 'categories_en',
 'origins',
 'origins_tags',
 'manufacturing_places',
 'manufacturing_places_tags',
 'labels',
 'labels_tags',
 'labels_en',
 'emb_codes',
 'emb_codes_tags',
 'first_packaging_code_geo',
 'cities',
 'cities_tags',
 'purchase_places',
 'stores',
 'countries',
 'countries_tags',
 'countries_en',
 'ingredients_text',
 'allergens',
 'allergens_en',
 'traces',
 'traces_tags',
 'traces_en',
 'serving_size',
 'no_nutriments',
 'additives_n',
 'additives',
 'additives_tags',
 'additives_en',
 'ingredients_from_palm_oil_n',
 'ingredients_from_palm_oil',
 'ingredients_from_palm_oil_tags',
 'ingredients_that_may_be_from_palm_oil_n',
 'ingredients_that_may_be_from_palm_oil',
 'ingredients_that_may_be_from_palm_oil_tags',
 'nutrition_grade_uk',
 'nutrition_grade_fr',
 'pnns_groups_1',
 'pnns_groups_2',
 'states',
 'states_tags',
 'states_en',
 'main_category',
 'main_category_en',
 'image_url',
 'image_small_url',
 'energy_100g',
 'energy-from-fat_100g',
 'fat_100g',
 'saturated-fat_100g',
 '-butyric-acid_100g',
 '-caproic-acid_100g',
 '-caprylic-acid_100g',
 '-capric-acid_100g',
 '-lauric-acid_100g',
 '-myristic-acid_100g',
 '-palmitic-acid_100g',
 '-stearic-acid_100g',
 '-arachidic-acid_100g',
 '-behenic-acid_100g',
 '-lignoceric-acid_100g',
 '-cerotic-acid_100g',
 '-montanic-acid_100g',
 '-melissic-acid_100g',
 'monounsaturated-fat_100g',
 'polyunsaturated-fat_100g',
 'omega-3-fat_100g',
 '-alpha-linolenic-acid_100g',
 '-eicosapentaenoic-acid_100g',
 '-docosahexaenoic-acid_100g',
 'omega-6-fat_100g',
 '-linoleic-acid_100g',
 '-arachidonic-acid_100g',
 '-gamma-linolenic-acid_100g',
 '-dihomo-gamma-linolenic-acid_100g',
 'omega-9-fat_100g',
 '-oleic-acid_100g',
 '-elaidic-acid_100g',
 '-gondoic-acid_100g',
 '-mead-acid_100g',
 '-erucic-acid_100g',
 '-nervonic-acid_100g',
 'trans-fat_100g',
 'cholesterol_100g',
 'carbohydrates_100g',
 'sugars_100g',
 '-sucrose_100g',
 '-glucose_100g',
 '-fructose_100g',
 '-lactose_100g',
 '-maltose_100g',
 '-maltodextrins_100g',
 'starch_100g',
 'polyols_100g',
 'fiber_100g',
 'proteins_100g',
 'casein_100g',
 'serum-proteins_100g',
 'nucleotides_100g',
 'salt_100g',
 'sodium_100g',
 'alcohol_100g',
 'vitamin-a_100g',
 'beta-carotene_100g',
 'vitamin-d_100g',
 'vitamin-e_100g',
 'vitamin-k_100g',
 'vitamin-c_100g',
 'vitamin-b1_100g',
 'vitamin-b2_100g',
 'vitamin-pp_100g',
 'vitamin-b6_100g',
 'vitamin-b9_100g',
 'folates_100g',
 'vitamin-b12_100g',
 'biotin_100g',
 'pantothenic-acid_100g',
 'silica_100g',
 'bicarbonate_100g',
 'potassium_100g',
 'chloride_100g',
 'calcium_100g',
 'phosphorus_100g',
 'iron_100g',
 'magnesium_100g',
 'zinc_100g',
 'copper_100g',
 'manganese_100g',
 'fluoride_100g',
 'selenium_100g',
 'chromium_100g',
 'molybdenum_100g',
 'iodine_100g',
 'caffeine_100g',
 'taurine_100g',
 'ph_100g',
 'fruits-vegetables-nuts_100g',
 'fruits-vegetables-nuts-estimate_100g',
 'collagen-meat-protein-ratio_100g',
 'cocoa_100g',
 'chlorophyl_100g',
 'carbon-footprint_100g',
 'nutrition-score-fr_100g',
 'nutrition-score-uk_100g',
 'glycemic-index_100g',
 'water-hardness_100g']

In [26]:
#Restricitng open foods dataset to columns of interest
newdf = openfood_df[['product_name', 'energy_100g', 'proteins_100g', 'carbohydrates_100g', 
                'fat_100g', 'saturated-fat_100g', 'fiber_100g', 'sugars_100g','countries','countries_en','brands','brands_tags', 'cholesterol_100g','trans-fat_100g','main_category_en']]
newdf.head()

,product_name,categories_en,energy_100g,proteins_100g,carbohydrates_100g,fat_100g,saturated-fat_100g,fiber_100g,sugars_100g,countries,countries_en,brands,brands_tags,cholesterol_100g,trans-fat_100g,main_category_en
0,Farine de blÃ© noir,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,en:FR,France,Ferme t'y R'nao,ferme-t-y-r-nao,NaN,NaN,NaN
1,Banana Chips Sweetened (Whole),NaN,2243.0,3.57,64.29,28.57,28.57,3.6,14.29,US,United States,NaN,NaN,0.018000000000000002,0.0,NaN
2,Peanuts,NaN,1941.0,17.86,60.71,17.86,0.0,7.1,17.86,US,United States,Torn & Glasser,torn-glasser,0.0,0.0,NaN
3,Organic Salted Nut Mix,NaN,2540.0,17.86,17.86,57.14,5.36,7.1,3.57,US,United States,Grizzlies,grizzlies,NaN,NaN,NaN
4,Organic Polenta,NaN,1552.0,8.57,77.14,1.43,NaN,5.7,NaN,US,United States,Bob's Red Mill,bob-s-red-mill,NaN,NaN,NaN

In [27]:
#Droping NA
df2=newdf.dropna()

In [28]:
#Deleting Repeating rows
cleaned_df = df2[df2['product_name']!='product_name'].copy().round(2)
cleaned_df.head()

,product_name,categories_en,energy_100g,proteins_100g,carbohydrates_100g,fat_100g,saturated-fat_100g,fiber_100g,sugars_100g,countries,countries_en,brands,brands_tags,cholesterol_100g,trans-fat_100g,main_category_en
185,Chaussons tressÃ©s aux pommes,"Sugary snacks,Biscuits and cakes,Pastries",1090.0,3.33,38.7,10.7,2.0,2.0,24.7,Canada,Canada,Kirkland Signature,kirkland-signature,0.00533,0.667,Sugary snacks
186,Pain Burger Artisan,fr:Boulange,1160.0,10.0,53.3,1.11,0.33299999999999996,2.22,1.11,Canada,Canada,Kirkland Signature,kirkland-signature,0.0,0.0,fr:Boulange
190,Quiche Lorraine,"Meals,Pizzas pies and quiches,Quiches,fr:Quich...",478.0,5.36,7.86,6.79,2.86,0.35700000000000004,0.7140000000000001,Canada,Canada,Kirkland Signature,kirkland-signature,0.0107,0.0,Meals
321,Sea Salt Potato Chips,"Chips and fries,Chips",2243.0,7.14,57.14,32.14,3.57,3.6,0.0,United States,United States,Trader Joe's,trader-joe-s,0.0,0.0,Chips and fries
505,Clam Chowder A Condensed Soup,"Meals,Soups,Chowders",276.0,4.1,9.02,1.64,0.0,0.8,0.82,United States,United States,Pilgrim Joe's,pilgrim-joe-s,0.008,0.0,Meals

In [29]:
#Creating list of categories to normalize
cleaned_df['main_category_en'].unique()

array(['Sugary snacks', 'fr:Boulange', 'Meals', 'Chips and fries',
       'Dairies', 'Plant-based foods and beverages', 'Groceries',
       'Pates-a-tartiner-aux-noisettes-et-au-cacao', 'Spreads',
       'Beverages', 'Fruit juices', 'Meats', 'Salty snacks',
       'Dietary supplements', 'Cake-mix', 'Mashed-potatoes',
       'Granola-mix', 'Mix', 'Coconut-creams', 'Coconut-waters',
       'Seafood', 'Beef-jerky', 'Banana-nut-loaf', 'Breakfasts',
       'Desserts', 'Balsamic-vinaigrette-dressing', 'Macaroni', 'Penne',
       'Peanut-butter-bliss', 'Beef-broth', 'Farming products', 'Soymilk',
       'Genoa-salami', 'Cottage-cheese', 'Popping-corn',
       'Goat-milk-cheese', 'Salsa', 'Garlic-mashed-potatoes',
       'Chocolate-with-raspberries', 'Tartar-sauce',
       'Whole-wheat-tortillas', 'Sweeteners', 'Frozen foods',
       'Canned-precooked-meat', 'Precooked-meat', 'Potato-crips',
       'Baked-beans', 'Senate-bean-soup', 'Freeze-dried foods',
       'Pierogies', 'Black-truffle-oil', 'Coconut-cream', 'Ramen',
       'Turkey-bacon', 'Stuffing', 'Snacks', 'fr:Produits-sous-licence',
       'Hot-cocoa-mix', 'Aliments-d-origine-vegetale', 'Canned foods',
       'fr:Tartinade-amandes-et-chocolat-noir', 'Cinnamon-raisin-bagels',
       'Pancakes-and-waffles', 'Hot-cocoa-powder', 'fr:Confit-de-dinde',
       'Pies', 'fr:Breuvage', 'Cheddar-baguettes', 'White-quinoa',
       'fr:Croustilles-chips', 'fr:Biscuits-aux-brisures-de-chocolat',
       'Marinara-sauce', 'Breaded products', 'fr:Kraft',
       'fr:Melange-a-soupe', 'fr:Mayonnaise-a-l-huile-d-olive',
       'fr:Miche-de-pain-fait-d-huile-d-olive', 'Feta-cheese', 'Matzos',
       'es:Sopas-instantaneas', 'Anchovy-paste', 'Cream-horseradish',
       'Horseradish-sauce', 'Hot-dog-mustard',
       'Blue-cheese-yogurt-dressing', 'Bruschetta', 'Cactus',
       'Fat-free-milk', 'Hot-fudge', 'Prosciutto',
       'fr:Tartinade-de-fromage-fondu', 'Capers', 'Pickles',
       'Hawaiian-sweet-rolls', 'fr:Pain-grains-germes-entiers',
       'Flour-tortillas', 'Mozzarella-sticks', 'Corn-tortilla-chips',
       'Cherry-pie-filling', 'Coffee-creamer', 'Salsa-chips',
       'Goat-milk-butter', 'Juices', 'Palm-sugar', 'Nonpareil-capers',
       'Cashews', 'Juice-drinks', 'Snack', 'Waffles', 'Whipping-cream',
       'fr:Quartiers-de-pamplemousse-rouge-prepare-dans-de-l-eau-legerement-sucree',
       'Diced-tomatoes', 'Fruit-and-nut-mix',
       'Milk-chocolate-filled-with-caramel', 'Green olives',
       'Chocolate-mints', 'Dry-seasoning-mix', 'Marshmallow-creme',
       'de:Blutenwasser', 'de:Rosenwasser', 'fr:Super-fruit',
       'fr:Viande-de-porc-preparee', 'fr:Burgers-de-boeuf', 'Tortillas',
       'fr:Marmelade-aux-figues', 'Pain-pita-sucres',
       'fr:Preparation-cremeuse-de-soya-pour-cuisiner',
       'fr:Pizza-toute-garnie-avec-croute-a-l-huile-d-olive',
       'fr:Le-chenevis-designe-la-graine-de-chanvre',
       'Seed-style-mustard', 'Vinegars', 'Sunflower-spread', 'Chocolat',
       'fr:Cretons', 'fr:Galette-de-boeuf', 'Tortilla-chips',
       'Indian-food', 'Curries', 'Kale-salads', 'fr:Beignes', 'Goat-milk',
       'fr:Tartinade', 'fr:Jus-de-pommes-et-fraises', 'Indian',
       'Breakfast-granola', 'Almond-milk-yogurt', 'Chips',
       'Cheese-analogues', 'fr:Sans-produit-laitier', 'fr:Simili-yogourt',
       'Chocolats', 'Hidden-valley', 'Pecans', 'fr:Oleagineux',
       'fr:Barre-nutritive', 'fr:Saucisson-aux-noix', 'Fresh foods',
       'Olives', 'fr:Beurre-de-noix-avec-noix-de-cajou', 'es:Atun',
       'es:Pan-dulce', 'es:Crema-de-cacahuate', 'es:Dulce-de-leche',
       'pt:Biscoito-salgado', 'fr:Biscoito',
       'fr:Sirop-d-erable-en-flocons', 'fr:Turrones', 'nl:Broodbeleggen',
       'fr:Pois-verts-au-wasabi', 'fr:Vermicelle', 'Spring-roll-pastry'],
      dtype=object)

In [33]:
#Saving list of unique category values as CSV to normalize
a = pd.Series(['Sugary snacks', 'fr:Boulange', 'Meals', 'Chips and fries',
       'Dairies', 'Plant-based foods and beverages', 'Groceries',
       'Pates-a-tartiner-aux-noisettes-et-au-cacao', 'Spreads',
       'Beverages', 'Fruit juices', 'Meats', 'Salty snacks',
       'Dietary supplements', 'Cake-mix', 'Mashed-potatoes',
       'Granola-mix', 'Mix', 'Coconut-creams', 'Coconut-waters',
       'Seafood', 'Beef-jerky', 'Banana-nut-loaf', 'Breakfasts',
       'Desserts', 'Balsamic-vinaigrette-dressing', 'Macaroni', 'Penne',
       'Peanut-butter-bliss', 'Beef-broth', 'Farming products', 'Soymilk',
       'Genoa-salami', 'Cottage-cheese', 'Popping-corn',
       'Goat-milk-cheese', 'Salsa', 'Garlic-mashed-potatoes',
       'Chocolate-with-raspberries', 'Tartar-sauce',
       'Whole-wheat-tortillas', 'Sweeteners', 'Frozen foods',
       'Canned-precooked-meat', 'Precooked-meat', 'Potato-crips',
       'Baked-beans', 'Senate-bean-soup', 'Freeze-dried foods',
       'Pierogies', 'Black-truffle-oil', 'Coconut-cream', 'Ramen',
       'Turkey-bacon', 'Stuffing', 'Snacks', 'fr:Produits-sous-licence',
       'Hot-cocoa-mix', 'Aliments-d-origine-vegetale', 'Canned foods',
       'fr:Tartinade-amandes-et-chocolat-noir', 'Cinnamon-raisin-bagels',
       'Pancakes-and-waffles', 'Hot-cocoa-powder', 'fr:Confit-de-dinde',
       'Pies', 'fr:Breuvage', 'Cheddar-baguettes', 'White-quinoa',
       'fr:Croustilles-chips', 'fr:Biscuits-aux-brisures-de-chocolat',
       'Marinara-sauce', 'Breaded products', 'fr:Kraft',
       'fr:Melange-a-soupe', 'fr:Mayonnaise-a-l-huile-d-olive',
       'fr:Miche-de-pain-fait-d-huile-d-olive', 'Feta-cheese', 'Matzos',
       'es:Sopas-instantaneas', 'Anchovy-paste', 'Cream-horseradish',
       'Horseradish-sauce', 'Hot-dog-mustard',
       'Blue-cheese-yogurt-dressing', 'Bruschetta', 'Cactus',
       'Fat-free-milk', 'Hot-fudge', 'Prosciutto',
       'fr:Tartinade-de-fromage-fondu', 'Capers', 'Pickles',
       'Hawaiian-sweet-rolls', 'fr:Pain-grains-germes-entiers',
       'Flour-tortillas', 'Mozzarella-sticks', 'Corn-tortilla-chips',
       'Cherry-pie-filling', 'Coffee-creamer', 'Salsa-chips',
       'Goat-milk-butter', 'Juices', 'Palm-sugar', 'Nonpareil-capers',
       'Cashews', 'Juice-drinks', 'Snack', 'Waffles', 'Whipping-cream',
       'fr:Quartiers-de-pamplemousse-rouge-prepare-dans-de-l-eau-legerement-sucree',
       'Diced-tomatoes', 'Fruit-and-nut-mix',
       'Milk-chocolate-filled-with-caramel', 'Green olives',
       'Chocolate-mints', 'Dry-seasoning-mix', 'Marshmallow-creme',
       'de:Blutenwasser', 'de:Rosenwasser', 'fr:Super-fruit',
       'fr:Viande-de-porc-preparee', 'fr:Burgers-de-boeuf', 'Tortillas',
       'fr:Marmelade-aux-figues', 'Pain-pita-sucres',
       'fr:Preparation-cremeuse-de-soya-pour-cuisiner',
       'fr:Pizza-toute-garnie-avec-croute-a-l-huile-d-olive',
       'fr:Le-chenevis-designe-la-graine-de-chanvre',
       'Seed-style-mustard', 'Vinegars', 'Sunflower-spread', 'Chocolat',
       'fr:Cretons', 'fr:Galette-de-boeuf', 'Tortilla-chips',
       'Indian-food', 'Curries', 'Kale-salads', 'fr:Beignes', 'Goat-milk',
       'fr:Tartinade', 'fr:Jus-de-pommes-et-fraises', 'Indian',
       'Breakfast-granola', 'Almond-milk-yogurt', 'Chips',
       'Cheese-analogues', 'fr:Sans-produit-laitier', 'fr:Simili-yogourt',
       'Chocolats', 'Hidden-valley', 'Pecans', 'fr:Oleagineux',
       'fr:Barre-nutritive', 'fr:Saucisson-aux-noix', 'Fresh foods',
       'Olives', 'fr:Beurre-de-noix-avec-noix-de-cajou', 'es:Atun',
       'es:Pan-dulce', 'es:Crema-de-cacahuate', 'es:Dulce-de-leche',
       'pt:Biscoito-salgado', 'fr:Biscoito',
       'fr:Sirop-d-erable-en-flocons', 'fr:Turrones', 'nl:Broodbeleggen',
       'fr:Pois-verts-au-wasabi', 'fr:Vermicelle', 'Spring-roll-pastry'])


a.to_csv("foodcategories2.csv")

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:62: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

In [41]:
#read category datagrame with new column set index to normalized category
csv_file_b = "foodcategories_norm.csv"
Openfoods_nrm_ctgry_df = pd.read_csv(csv_file_b)
Openfoods_nrm_ctgry_df = Openfoods_nrm_ctgry_df.rename(columns={'Food_Categories': 'main_category_en'})
#FAO_nrm_ctgry_df = FAO_nrm_ctgry_df.set_index('normalized_category')
Openfoods_nrm_ctgry_df.head()

  main_category_en Normalized_Category
0    Sugary snacks             'Sweet'
1      fr:Boulange               Other
2            Meals               Other
3  Chips and fries           Dry_Goods
4          Dairies               Dairy

In [42]:
# Merging normalized categories to the cleaned open foods dataframe
ofd_clean_norm_df = pd.merge(cleaned_df, Openfoods_nrm_ctgry_df, on='main_category_en', how='left')
ofd_clean_norm_df.head()

,product_name,categories_en,energy_100g,proteins_100g,carbohydrates_100g,fat_100g,saturated-fat_100g,fiber_100g,sugars_100g,countries,countries_en,brands,brands_tags,cholesterol_100g,trans-fat_100g,main_category_en,Normalized_Category
0,Chaussons tressÃ©s aux pommes,"Sugary snacks,Biscuits and cakes,Pastries",1090.0,3.33,38.7,10.7,2.0,2.0,24.7,Canada,Canada,Kirkland Signature,kirkland-signature,0.00533,0.667,Sugary snacks,'Sweet'
1,Pain Burger Artisan,fr:Boulange,1160.0,10.0,53.3,1.11,0.33299999999999996,2.22,1.11,Canada,Canada,Kirkland Signature,kirkland-signature,0.0,0.0,fr:Boulange,Other
2,Quiche Lorraine,"Meals,Pizzas pies and quiches,Quiches,fr:Quich...",478.0,5.36,7.86,6.79,2.86,0.35700000000000004,0.7140000000000001,Canada,Canada,Kirkland Signature,kirkland-signature,0.0107,0.0,Meals,Other
3,Sea Salt Potato Chips,"Chips and fries,Chips",2243.0,7.14,57.14,32.14,3.57,3.6,0.0,United States,United States,Trader Joe's,trader-joe-s,0.0,0.0,Chips and fries,Dry_Goods
4,Clam Chowder A Condensed Soup,"Meals,Soups,Chowders",276.0,4.1,9.02,1.64,0.0,0.8,0.82,United States,United States,Pilgrim Joe's,pilgrim-joe-s,0.008,0.0,Meals,Other

In [ ]:
#Merging the two normalized datasets
ofd_fao_norm_df = pd.merge(ofd_clean_norm_df, fao_norm_df, on='Normalized_Category', how='left')
ofd_fao_norm_df.to_csv('ofd_fao_norm_df.csv')

In [ ]:
# sum of merged data frames grouped by normalized category
ctgry_grp_sum = ofd_fao_norm_df.groupby('Normalized_Category').sum()
ctgry_grp_sum.head()